// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int n = Integer.parseInt(args[0]);
		int less = 0;
		int bigger = 0;
		for(int i = 0; i < n; i++){
			Double random = Math.random();
			if(random <= 0.5){
				less++;
			}else{
				bigger ++;
			}
		}System.out.println("<= 0.5: " + less + " times");
		System.out.println("> 0.5: " + bigger + " times");
		Double ratio = (double)less / bigger;
		if((less != 0) && (bigger != 0)){
		System.out.println("Ratio: " + ratio);
		}
		}
	}

